// Vite/Astro plugin — 在构建时扫描 src/themes/ 并生成主题清单
//
// 产物: src/generated/themes.ts  (被 Astro 组件直接 import)
//
// 重建时机:
//   - 任何 src/themes/** 下的文件变动
//   - dev server 启动时
//   - build 时

import { readdirSync, readFileSync, statSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// astro-plugins/theme-loader.mjs → 项目根 = ../
// themes dir = ../src/themes
// generated dir = ../src/generated
const ROOT = join(__dirname, '..');
const THEMES_DIR = join(ROOT, 'src', 'themes');
const OUT_DIR = join(ROOT, 'src', 'generated');
const OUT_FILE = join(OUT_DIR, 'themes.ts');

function scan() {
  if (!existsSync(THEMES_DIR)) return [];
  const dirs = readdirSync(THEMES_DIR).filter((n) => statSync(join(THEMES_DIR, n)).isDirectory());
  const themes = [];
  for (const id of dirs) {
    const manifestPath = join(THEMES_DIR, id, 'manifest.json');
    if (!existsSync(manifestPath)) continue;
    try {
      const parsed = JSON.parse(readFileSync(manifestPath, 'utf-8'));
      if (!parsed.id || !parsed.name || !Array.isArray(parsed.modes)) continue;
      themes.push({
        id: parsed.id,
        name: parsed.name,
        author: parsed.author || 'unknown',
        version: parsed.version || '0.0.0',
        description: parsed.description || '',
        modes: parsed.modes.filter((m) => m === 'light' || m === 'dark'),
        preview: parsed.preview || '',
      });
    } catch (e) {
      console.warn(`[theme-loader] Skipping "${id}":`, e.message);
    }
  }
  // 排序: atom-default 优先
  themes.sort((a, b) => {
    if (a.id === 'atom-default') return -1;
    if (b.id === 'atom-default') return 1;
    return a.id.localeCompare(b.id);
  });
  return themes;
}

function emit(themes) {
  mkdirSync(OUT_DIR, { recursive: true });
  const json = JSON.stringify(themes, null, 2);
  const content = `// ⚠️ AUTO-GENERATED by astro-plugins/theme-loader.mjs — do not edit
// Regenerate by running dev/build (or delete this file to force rebuild).

import type { ThemeManifest } from '../utils/themes';

export const themes: ThemeManifest[] = ${json};
`;
  // 仅当内容变化时写盘（避免触发无限 HMR）
  let prev = '';
  try { prev = readFileSync(OUT_FILE, 'utf-8'); } catch {}
  if (prev !== content) {
    writeFileSync(OUT_FILE, content, 'utf-8');
    console.log(`[theme-loader] Generated ${themes.length} theme(s) → ${OUT_FILE.replace(ROOT + '/', '')}`);
  }
}

export default function themeLoaderPlugin() {
  let server;
  return {
    name: 'atom-theme-loader',
    buildStart() {
      emit(scan());
    },
    configureServer(s) {
      server = s;
      // 监听 themes 目录变化
      try {
        s.watcher.add(THEMES_DIR);
        s.watcher.on('change', (file) => {
          if (file.startsWith(THEMES_DIR)) {
            emit(scan());
            // 通知客户端刷新（CSS 已在 HMR）
            server.ws.send({ type: 'full-reload' });
          }
        });
      } catch {}
    },
    handleHotUpdate({ file }) {
      if (file.startsWith(THEMES_DIR)) {
        emit(scan());
      }
    },
  };
}