// Vite/Astro plugin — 在构建时扫描 src/themes/ 并生成:
//   1. src/generated/themes.ts       类型安全的主题清单（被 Astro 组件 import）
//   2. src/generated/themes.css      所有主题的 CSS 入口（被 global.css @import）
//
// 重建时机:
//   - 任何 src/themes/** 下的文件变动
//   - dev server 启动时
//   - build 时

import { readdirSync, readFileSync, statSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// astro-plugins/theme-loader.mjs → 项目根 = ../
const ROOT = join(__dirname, '..');
const THEMES_DIR = join(ROOT, 'src', 'themes');
const OUT_DIR = join(ROOT, 'src', 'generated');
const OUT_TS = join(OUT_DIR, 'themes.ts');
const OUT_CSS = join(OUT_DIR, 'themes.css');

/**
 * 主题 ID 合法性校验（与 src/utils/themes.ts 保持同步）。
 * 防止 XSS 或文件系统遍历。
 */
const SAFE_ID = /^[a-z0-9][a-z0-9_-]{0,31}$/;
function isValidThemeId(id) {
  return SAFE_ID.test(id);
}

function scan() {
  if (!existsSync(THEMES_DIR)) return [];
  const dirs = readdirSync(THEMES_DIR).filter((n) => statSync(join(THEMES_DIR, n)).isDirectory());
  const themes = [];
  for (const id of dirs) {
    if (!isValidThemeId(id)) {
      console.warn(`[theme-loader] Skipping "${id}": invalid id (must match ${SAFE_ID})`);
      continue;
    }
    const manifestPath = join(THEMES_DIR, id, 'manifest.json');
    if (!existsSync(manifestPath)) {
      console.warn(`[theme-loader] Skipping "${id}": no manifest.json`);
      continue;
    }
    try {
      const parsed = JSON.parse(readFileSync(manifestPath, 'utf-8'));
      if (!parsed.id || !parsed.name || !Array.isArray(parsed.modes) || parsed.modes.length === 0) {
        console.warn(`[theme-loader] Skipping "${id}": invalid manifest (missing id/name/modes)`);
        continue;
      }
      // 检测实际存在的 mode 文件（manifest 可能声明但文件缺失）
      const availableModes = parsed.modes.filter((m) => {
        if (m !== 'light' && m !== 'dark') return false;
        return existsSync(join(THEMES_DIR, id, `${m}.css`));
      });
      if (availableModes.length === 0) {
        console.warn(`[theme-loader] Skipping "${id}": no light.css / dark.css found`);
        continue;
      }
      themes.push({
        id: parsed.id,
        name: parsed.name,
        author: parsed.author || 'unknown',
        version: parsed.version || '0.0.0',
        description: parsed.description || '',
        modes: availableModes,
        preview: parsed.preview || '',
      });
    } catch (e) {
      console.warn(`[theme-loader] Skipping "${id}":`, e.message);
    }
  }
  // 排序: atom-default 优先
  themes.sort((a, b) => {
    if (a.id === 'atom-default') return -1;
    if (b.id === 'atom-default') return 1;
    return a.id.localeCompare(b.id);
  });
  return themes;
}

function emitTs(themes) {
  mkdirSync(OUT_DIR, { recursive: true });
  const json = JSON.stringify(themes, null, 2);
  const content = `// ⚠️ AUTO-GENERATED by astro-plugins/theme-loader.mjs — do not edit
// Regenerate by running dev/build (or delete this file to force rebuild).

import type { ThemeManifest } from '../utils/themes';

export const themes: ThemeManifest[] = ${json};
`;

  let prev = '';
  try { prev = readFileSync(OUT_TS, 'utf-8'); } catch {}
  if (prev !== content) {
    writeFileSync(OUT_TS, content, 'utf-8');
    console.log(`[theme-loader] Generated ${themes.length} theme(s) → ${OUT_TS.replace(ROOT + '/', '')}`);
  }
}

function emitCss(themes) {
  mkdirSync(OUT_DIR, { recursive: true });
  // 仅生成 @import 语句；CSS 内容由源文件提供（保留开发者注释与可调试性）
  const lines = themes.flatMap((t) => {
    const out = [];
    if (t.modes.includes('light')) {
      out.push(`@import '../themes/${t.id}/light.css';`);
    }
    if (t.modes.includes('dark')) {
      out.push(`@import '../themes/${t.id}/dark.css';`);
    }
    return out;
  });

  const header = `/* ⚠️ AUTO-GENERATED by astro-plugins/theme-loader.mjs — do not edit.
 * Aggregates all theme CSS files. Regenerate by running dev/build
 * (or delete this file to force rebuild).
 *
 * To add a new theme: drop a directory under src/themes/<id>/ with
 * manifest.json + light.css (+ optional dark.css) — this file updates
 * automatically.
 */`;
  const content = `${header}\n${lines.join('\n')}\n`;

  let prev = '';
  try { prev = readFileSync(OUT_CSS, 'utf-8'); } catch {}
  if (prev !== content) {
    writeFileSync(OUT_CSS, content, 'utf-8');
    console.log(`[theme-loader] Generated CSS entry → ${OUT_CSS.replace(ROOT + '/', '')} (${lines.length} @imports)`);
  }
}

function emitAll() {
  const themes = scan();
  emitTs(themes);
  emitCss(themes);
  return themes;
}

export default function themeLoaderPlugin() {
  let server;
  return {
    name: 'atom-theme-loader',
    buildStart() {
      emitAll();
    },
    configureServer(s) {
      server = s;
      try {
        s.watcher.add(THEMES_DIR);
        s.watcher.on('change', (file) => {
          if (file.startsWith(THEMES_DIR)) {
            emitAll();
            // CSS 已在 HMR；同时 themes.ts 变化需要 full-reload 才能让 Astro 重新 import
            server.ws.send({ type: 'full-reload' });
          }
        });
        s.watcher.on('add', (file) => {
          if (file.startsWith(THEMES_DIR)) {
            emitAll();
            server.ws.send({ type: 'full-reload' });
          }
        });
      } catch {}
    },
    handleHotUpdate({ file }) {
      if (file.startsWith(THEMES_DIR)) {
        emitAll();
      }
    },
  };
}